common:
	@sh components/common.sh

frontend:
	@sh components/frontend.sh

mongo:
	@sh components/mongo.sh

catalogue:
	@sh components/catalogue.sh

redis:
	@sh components/redis.sh

user:
	@sh components/user.sh

cart:
	@sh components/cart.sh