common:
	@sh components/common.sh

frontend:
	@sh components/frontend.sh

mongo:
	@sh components/mongo.sh

catalogue:
	@sh components/catalogue.sh

redis:
	@sh components/redis.sh

user:
	@sh components/user.sh

cart:
	@sh components/cart.sh

mysql:
	@sh components/mysql.sh

payment:
	@sh components/payment.sh

rabbitmq:
	@sh components/rabbitmq.sh

shipping:
	@sh components/shipping.sh
